#!/bin/bash

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
SOURCE_CASE="$REPO_ROOT/tutorials/vacuumLaserbeamFoam/wang2020_304L_nearVacuum"
RUN_CASE="$REPO_ROOT/tests/run/wang304LMatchedSmoke"

rm -rf "$RUN_CASE"
mkdir -p "$RUN_CASE"
cp -a "$SOURCE_CASE/initial" "$RUN_CASE/"
cp -a "$SOURCE_CASE/constant" "$RUN_CASE/"
cp -a "$SOURCE_CASE/system" "$RUN_CASE/"

cd "$RUN_CASE"

cp system/blockMeshDict.smoke8um system/blockMeshDict
cp system/controlDict.smoke10us system/controlDict

echo "Copying 'initial' to 0"
cp -r initial 0

. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication setFields
runApplication decomposePar
runParallel vacuumLaserbeamFoam

"$SCRIPT_DIR/Check"
