#!/bin/bash

rm -rf 0 [1-9]* processor* postProcessing VTKs
rm -rf constant/polyMesh
rm -f log.* case.foam run.pid
rm -f system/setFieldsDict
rm -f constant/powderParticles.csv constant/powderManifest.json
rm -f movingKeyholeDepth.csv
