#!/bin/bash

cp system/controlDict.reference system/controlDict

if [ -f log.vacuumLaserbeamFoam ]; then
    LAST_LOG_TIME=$(grep '^[[:space:]]*Time = ' log.vacuumLaserbeamFoam | tail -1 | awk '{print $3}')
    if [ -n "$LAST_LOG_TIME" ]; then
        mv log.vacuumLaserbeamFoam "log.vacuumLaserbeamFoam.to_$LAST_LOG_TIME"
    else
        mv log.vacuumLaserbeamFoam log.vacuumLaserbeamFoam.previous
    fi
fi

nohup mpirun -np 48 vacuumLaserbeamFoam -parallel > log.vacuumLaserbeamFoam 2>&1 &
echo $! > run.pid

echo "Resumed 4 um Wang 304L reference run from latest processor time."
echo "PID: $(cat run.pid)"
echo "Target simulation time: 140 us"
echo "MPI ranks: 48"
echo "Use ./Status to inspect progress."
