#!/bin/bash

nohup ./Allrun.reference > log.Allrun 2>&1 &
echo $! > run.pid

echo "Started 4 um Wang 304L reference run in background."
echo "PID: $(cat run.pid)"
echo "Target simulation time: 120 us"
echo "MPI ranks: 48"
echo "Use ./Status to inspect progress."
